/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type InternalCheatsTransformer from '#app/internal/transformers/cheats_transformer'
import type UsersTokenTransformer from '#app/users/transformers/token_transformer'
import type UsersUserTransformer from '#app/users/transformers/user_transformer'
import type InertiaMiddleware from '#core/middleware/inertia_middleware'

export namespace Data {
  export namespace Internal {
    export type Cheats = InferData<InternalCheatsTransformer>
    export namespace Cheats {
      export type Variants = InferVariants<InternalCheatsTransformer>
    }
  }
  export namespace Users {
    export type Token = InferData<UsersTokenTransformer>
    export namespace Token {
      export type Variants = InferVariants<UsersTokenTransformer>
    }
    export type User = InferData<UsersUserTransformer>
    export namespace User {
      export type Variants = InferVariants<UsersUserTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
