/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CheatSchema extends BaseModel {
  static $columns = ['createdAt', 'domain', 'observedAt', 'updatedAt', 'userUuid', 'uuid'] as const
  $columns = CheatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare domain: string | null
  @column.dateTime()
  declare observedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
  @column({ isPrimary: true })
  declare uuid: string
}

export class ExamUserSchema extends BaseModel {
  static $columns = ['createdAt', 'examUuid', 'id', 'userUuid'] as const
  $columns = ExamUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare examUuid: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userUuid: string
}

export class ExamSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUuid', 'description', 'endsAt', 'schoolUuid', 'startsAt', 'title', 'updatedAt', 'uuid'] as const
  $columns = ExamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUuid: string | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare endsAt: DateTime
  @column()
  declare schoolUuid: string
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class GroupUserSchema extends BaseModel {
  static $columns = ['createdAt', 'groupUuid', 'id', 'userUuid'] as const
  $columns = GroupUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupUuid: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userUuid: string
}

export class GroupSchema extends BaseModel {
  static $columns = ['createdAt', 'name', 'schoolUuid', 'slug', 'updatedAt', 'uuid'] as const
  $columns = GroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare name: string
  @column()
  declare schoolUuid: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'isSystem', 'name', 'permissions', 'schoolUuid', 'updatedAt', 'uuid'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare permissions: any
  @column()
  declare schoolUuid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class SchoolInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'invitedByUuid', 'roleUuid', 'schoolUuid', 'updatedAt', 'uuid'] as const
  $columns = SchoolInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare invitedByUuid: string | null
  @column()
  declare roleUuid: string | null
  @column()
  declare schoolUuid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class SchoolSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'name', 'slug', 'updatedAt', 'uuid'] as const
  $columns = SchoolSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class StudentProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'publicKey', 'updatedAt', 'userUuid'] as const
  $columns = StudentProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare publicKey: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userUuid: string
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'roleUuid', 'userUuid'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleUuid: string
  @column()
  declare userUuid: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'ferrisUuid', 'fullName', 'schoolUuid', 'updatedAt', 'uuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare ferrisUuid: string | null
  @column()
  declare fullName: string | null
  @column()
  declare schoolUuid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}
