import { configApp } from '@adonisjs/eslint-config'

export default configApp({
  // Framework-owned output: regenerated by `node ace codegen` and by migrations.
  ignores: ['.adonisjs/**', 'build/**', 'app/core/database/schema.ts'],
})
