/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Auth: () => import('#app/auth/controllers/auth_controller'),
  },
  internal: {
    Internal: () => import('#app/internal/controllers/internal_controller'),
  },
  public: {
    Public: () => import('#app/public/controllers/public_controller'),
  },
  users: {
    Impersonates: () => import('#app/users/controllers/impersonates_controller'),
    Invite: () => import('#app/users/controllers/invite_controller'),
    Password: () => import('#app/users/controllers/password_controller'),
    Profile: () => import('#app/users/controllers/profile_controller'),
    Settings: () => import('#app/users/controllers/settings_controller'),
    Tokens: () => import('#app/users/controllers/tokens_controller'),
    Users: () => import('#app/users/controllers/users_controller'),
  },
}
