/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import InternalBusted from '#app/internal/events/busted'

export const events = {
  internal: {
    Busted: InternalBusted,
  },
}
